server:
  port: 8084

spring:
  application:
    name: crop-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/crop_db

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/